# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gmaps_v3}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wilker Lucio"]
  s.date = %q{2010-04-12}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{wilkerlucio@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gmaps_v3.gemspec",
     "lib/gmaps_v3.rb",
     "rails/init.rb",
     "spec/gmaps_v3_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/wilkerlucio/gmaps_v3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{GMaps v3 enable simple integration with Google Maps API v3}
  s.test_files = [
    "spec/gmaps_v3_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simplehttp>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<simplehttp>, [">= 0.1.3"])
      s.add_dependency(%q<json>, [">= 1.2.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<simplehttp>, [">= 0.1.3"])
    s.add_dependency(%q<json>, [">= 1.2.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

